name: Schedule Upgrade Requirements

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
    inputs:
      branch:
        description: "Target branch to create requirements PR against"
        required: true
        default: 'master'

jobs:
  call-upgrade-python-requirements-workflow:
    with: 
      branch: "$(if ['${{ inputs.branch }}' = '']; then echo 'master'; else echo '${{ inputs.branch }}'; fi)"
    uses: /workflow-templates/upgrade-python-requirements.yml