name: Upgrade Requirements

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:
    inputs:
      branch:
        description: "Target branch to create requirements PR against"
        required: true
        default: "master"

jobs:
  call-upgrade-python-requirements-workflow:
    with:
      branch: ${{ github.event.inputs.branch }}
      team_reviewers: "arbi_bom"
      email_address: "arbi-bom@edx.org"

    uses: edx/.github/.github/workflows/upgrade-python-requirements.yml@master
