name: merge-upgrade-prs

on:
  pull_request:
  schedule:
    - cron: "0 7 * * *"
jobs:
  get-list:
    runs-on: ubuntu-20.04
    
    outputs:
      urls: ${{ steps.generate-matrix.outputs.urls }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: openedx/tubular
          ref: iamsobanjaved/enhance
          path: tubular

      - name: setup tubular
        run: |
          cd tubular
          pip install -e .
      - name: Run script
        env:
          GIT_TOKEN: ${{ github.token }}
        run: |
          get_ready_to_merge_prs.py --org openedx
          get_ready_to_merge_prs.py --org openedx | sed '1d;2d;'
          echo "urls=$(get_ready_to_merge_prs.py --org openedx | sed '1d;2d;')" >> $GITHUB_OUTPUT
      - name: Generate Matrix
        env:
          GIT_TOKEN: ${{ github.token }}
        id: generate-matrix
        run: |
          echo "urls=$(get_ready_to_merge_prs.py --org openedx | sed '1d;2d;')" >> $GITHUB_OUTPUT
  
  merge_pr:
    runs-on: ubuntu-20.04
    needs:
      - get-list
    strategy:
      matrix:
        url: ${{ fromJSON(needs.get-list.outputs.urls) }}

    steps:

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: openedx/tubular
          path: tubular
          
      - name: setup tubular
        run: |
          cd tubular
          pip install -e .
          
      - name: run command
        env:
          GIT_TOKEN: ${{ github.token }} 
        run: |
          url="${{ matrix.url }}"
      
          # Extract the organization name
          org_name=$(echo $url | awk -F/ '{print $4}')
          

          # Extract the repo name
          repo_name=$(echo $url | awk -F/ '{print $5}')

          # Extract the pull request number
          pr_number=$(echo $url | awk -F/ '{print $7}')
          
          #print out
          echo "Organization: $org_name"
          echo "Repo: $repo_name"
          echo "PR: $pr_number"
          
          cd tubular
          check_pr_tests_status.py --org "$org_name" --repo "$repo_name" --pr_number "$pr_number"
